#!/usr/bin/env bash
# Sync wiki/ to a Windows-accessible path for Obsidian.
# WSL2 can't run Obsidian natively, and Windows Obsidian can't read the Linux FS.
# This syncs to /mnt/c/ or a custom Windows path.
source "$(dirname "$0")/lib.sh"

# Default sync target — user's Windows home Documents folder
WIN_USER="${WIN_USER:-$(cmd.exe /c "echo %USERNAME%" 2>/dev/null | tr -d '\r')}"
DEFAULT_TARGET="/mnt/c/Users/${WIN_USER}/Documents/research-wiki-vault"
SYNC_TARGET="${OBSIDIAN_SYNC_TARGET:-$DEFAULT_TARGET}"

log_info "=== Syncing wiki/ to Windows for Obsidian ==="
log_info "Source: ${WIKI_DIR}"
log_info "Target: ${SYNC_TARGET}"

# Create target if needed
mkdir -p "$SYNC_TARGET"

# Rsync wiki/ to Windows path
# --delete keeps them in sync (removes files deleted from wiki/)
# --exclude .obsidian/workspace* (user-specific, regenerated by Obsidian)
rsync -av --delete \
    --exclude=".gitkeep" \
    "${WIKI_DIR}/" "${SYNC_TARGET}/"

if [ $? -eq 0 ]; then
    log_info "Sync complete: ${SYNC_TARGET}"
    log_info "Open Obsidian on Windows → Open folder as vault → ${SYNC_TARGET}"
else
    log_error "Sync failed"
    exit 1
fi

log_info "=== Done ==="
log_info "Tip: Run this after every ingestion, or set up a cron/watch:"
log_info "  watch -n 30 ./scripts/sync-obsidian.sh"
log_info "  Or set OBSIDIAN_SYNC_TARGET to customize the path"
