#!/usr/bin/env python3
"""
tools/state.py — Regenerate `.cursor/` common-state surface.

Per operator directive 2026-05-09 turn 8: a gitignored per-system cache of
pre-rendered project state for `/view`, `/questions`, and any other
operator/AI surface to read quickly.

Usage:
    .venv/bin/python -m tools.state regenerate              # all files
    .venv/bin/python -m tools.state regenerate view         # just view-snapshot.md
    .venv/bin/python -m tools.state regenerate questions    # just questions-snapshot.md
    .venv/bin/python -m tools.state regenerate vision       # just vision.md
    .venv/bin/python -m tools.state regenerate focus        # just focus.md
    .venv/bin/python -m tools.state regenerate trace        # just trace.md
    .venv/bin/python -m tools.state status                  # what's stale
    .venv/bin/python -m tools.state show <file>             # cat a snapshot

Source-of-truth: wiki/ + git + raw/notes/ + .assistant/ — the regenerator
just synthesizes these into the .cursor/ render-cache. Loss of .cursor/ is
fully recoverable from sources.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(os.environ.get("CLAUDE_PROJECT_DIR", "/home/jfortin/devops-solutions-information-hub"))
CURSOR_DIR = PROJECT_ROOT / ".cursor"
META_PATH = CURSOR_DIR / "_meta.json"


# ─────────── helpers ────────────


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def git(*args: str) -> str:
    try:
        return subprocess.check_output(["git", "-C", str(PROJECT_ROOT), *args], text=True, stderr=subprocess.STDOUT).strip()
    except subprocess.CalledProcessError as e:
        return f"(git error: {e.output.strip()})"


def hash_inputs(*paths: Path) -> str:
    h = hashlib.sha256()
    for p in paths:
        if p.is_file():
            h.update(p.read_bytes())
        elif p.is_dir():
            for f in sorted(p.rglob("*.md")):
                h.update(f.read_bytes())
    return h.hexdigest()[:16]


def load_meta() -> dict:
    if META_PATH.exists():
        with open(META_PATH) as f:
            return json.load(f)
    return {"schema_version": 1, "files": {}}


def save_meta(meta: dict) -> None:
    CURSOR_DIR.mkdir(parents=True, exist_ok=True)
    with open(META_PATH, "w") as f:
        json.dump(meta, f, indent=2)


def regenerator() -> str:
    """Identifier of the regenerating actor — assistant name or 'operator-manual'."""
    return os.environ.get("ASSISTANT_PROFILE", os.environ.get("USER", "manual"))


# ─────────── regen: view-snapshot.md (the 7-section /view cache) ────────────


def regen_view() -> str:
    """Build the 7-section /view snapshot from current project state."""
    out = []
    out.append("# View Snapshot — Pre-rendered for /view\n")
    out.append(f"_Auto-regenerated by `tools.state regenerate` at {now_iso()}._\n\n")
    out.append("This is a CACHE. The `/view` slash command may read this for fast render OR ")
    out.append("re-synthesize live from sources per its shape-detection logic. Sources:\n")
    out.append("`wiki/` + git + `.assistant/` + `wiki/backlog/` + `raw/notes/`.\n\n")
    out.append("---\n\n")

    # ─── 1. PROGRESS ───
    out.append("## 1. PROGRESS — trajectory + trend\n\n")
    log_25 = git("log", "--oneline", "-25")
    out.append("### Recent 25 commits\n\n```\n")
    out.append(log_25 + "\n")
    out.append("```\n\n")
    # Commit cadence
    last_month = git("log", "--since=30.days.ago", "--oneline")
    commits_30d = len([l for l in last_month.splitlines() if l.strip()])
    out.append(f"### Cadence: {commits_30d} commits in the last 30 days\n\n")
    # Recent wiki/log/ entries
    log_dir = PROJECT_ROOT / "wiki" / "log"
    if log_dir.exists():
        recent_logs = sorted(log_dir.glob("2026-*.md"), reverse=True)[:5]
        if recent_logs:
            out.append("### Recent session logs\n\n")
            for p in recent_logs:
                out.append(f"- [`{p.name}`](wiki/log/{p.name})\n")
            out.append("\n")
    out.append("### Trend annotation\n\n")
    out.append("*(Synthesized from commit cadence + recent log titles. `/view` skill may re-synthesize.)*\n\n")
    out.append("---\n\n")

    # ─── 2. POSITION ───
    out.append("## 2. POSITION — current state\n\n")
    branch = git("branch", "--show-current")
    status_short = git("status", "--short")
    last_commit_subj = git("log", "-1", "--pretty=%s")
    last_commit_when = git("log", "-1", "--pretty=%cr")
    ahead_behind = git("status", "--short", "--branch")
    out.append("| Fact | Value |\n|---|---|\n")
    out.append(f"| Branch | `{branch}` |\n")
    out.append(f"| Last commit | {last_commit_subj} |\n")
    out.append(f"| Last commit age | {last_commit_when} |\n")
    out.append(f"| Branch tracking | {ahead_behind.splitlines()[0] if ahead_behind else '(clean)'} |\n")
    wc = len([l for l in status_short.splitlines() if l.strip()])
    out.append(f"| Uncommitted file changes | {wc} |\n")
    out.append("\n### Working tree state\n\n```\n")
    out.append(status_short or "(clean)\n")
    out.append("\n```\n\n---\n\n")

    # ─── 3. DONE ───
    out.append("## 3. DONE — shipped items\n\n")
    out.append("*(Synthesized from recent commits + maturity-promoted lessons.)*\n\n")
    recent_merges = git("log", "--oneline", "-20", "--no-merges")
    out.append("### Recent shipped (last 20 commits)\n\n```\n")
    out.append(recent_merges + "\n")
    out.append("```\n\n---\n\n")

    # ─── 4. TODO ───
    out.append("## 4. TODO — remaining work\n\n")
    backlog_idx = PROJECT_ROOT / "wiki" / "backlog" / "_index.md"
    if backlog_idx.exists():
        out.append(f"### Backlog state (see `wiki/backlog/_index.md`)\n\n")
        # Top of backlog index — summary
        text = backlog_idx.read_text()
        # Just show first 60 lines or until first table closes
        lines = text.splitlines()[:60]
        out.append("```\n" + "\n".join(lines) + "\n```\n\n")
    # In-code TODOs
    try:
        proc = subprocess.run(
            ["rg", "-i", "-n", "TODO|FIXME|XXX", "-g", "!.venv", "-g", "!node_modules", "-g", "!wiki/*", str(PROJECT_ROOT)],
            capture_output=True, text=True, timeout=30
        )
        todos = proc.stdout.strip().splitlines()[:15]
        if todos:
            out.append("### In-code TODOs (capped at 15)\n\n```\n")
            for t in todos:
                # Strip absolute path
                out.append(t.replace(str(PROJECT_ROOT) + "/", "") + "\n")
            out.append("```\n\n")
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    out.append("---\n\n")

    # ─── 5. QUESTIONS — link to questions-snapshot.md ───
    out.append("## 5. QUESTIONS — answered + unanswered\n\n")
    out.append("See `.cursor/questions-snapshot.md` for full mini-RFC per open question.\n\n")
    # Brief summary from operator-decision-queue
    odq = PROJECT_ROOT / "wiki" / "backlog" / "operator-decision-queue.md"
    if odq.exists():
        # Count strikethrough rows (resolved) vs open
        text = odq.read_text()
        resolved = text.count("~~")
        open_q_lines = [l for l in text.splitlines() if l.strip().startswith("| ") and "~~" not in l and "RESOLVED" not in l]
        out.append(f"- Operator-decision queue strikethrough markers: {resolved}\n")
        out.append(f"- Source: `wiki/backlog/operator-decision-queue.md`\n\n")
    out.append("---\n\n")

    # ─── 6. WAY FORWARD ───
    out.append("## 6. WAY FORWARD — candidate threads\n\n")
    out.append("*(Synthesized from latest session log + open backlog items + operator-stated forward direction.)*\n\n")
    # Latest session log forward-direction (best-effort: pull last log's tail)
    recent_logs = sorted((PROJECT_ROOT / "wiki" / "log").glob("2026-*.md"), reverse=True) if (PROJECT_ROOT / "wiki" / "log").exists() else []
    if recent_logs:
        out.append(f"### From most-recent log: `{recent_logs[0].name}`\n\n")
        out.append(f"See: `wiki/log/{recent_logs[0].name}` for the operator-stated forward direction + pickup-cold runbook (if present).\n\n")
    out.append("---\n\n")

    # ─── 7. SIGNPOSTS ───
    out.append("## 7. SIGNPOSTS — where to find what\n\n")
    out.append("| Where | What |\n|---|---|\n")
    out.append("| `CLAUDE.md` | Operational program (every-message hot path) |\n")
    out.append("| `AGENTS.md` | Universal cross-tool rules |\n")
    out.append("| `CONTEXT.md` | Identity profile + active epics |\n")
    out.append("| `.claude/rules/` | On-demand rules (routing · methodology · learnings · etc.) |\n")
    out.append("| `wiki/log/` (latest 3) | Recent session work + handoffs |\n")
    out.append("| `wiki/backlog/operator-decision-queue.md` | Operator decisions (answered + open) |\n")
    out.append("| `wiki/backlog/research-gaps.md` | Empirical research questions |\n")
    out.append("| `wiki/spine/super-model/super-model.md` | What this system IS |\n")
    out.append("| `wiki/spine/references/model-registry.md` | 16 models + standards + adoption tiers |\n")
    out.append("| `.assistant/` | Per-Project Assistant Profiles + vendor configs + CRON + surfaces |\n")
    out.append("| `.cursor/` | This state cache (per-system, gitignored) |\n")
    out.append("\n")

    return "".join(out)


# ─────────── regen: questions-snapshot.md ────────────


def regen_questions() -> str:
    out = []
    out.append("# Questions Snapshot — Pre-rendered for /questions\n\n")
    out.append(f"_Auto-regenerated by `tools.state regenerate` at {now_iso()}._\n\n")
    out.append("Source: `wiki/backlog/operator-decision-queue.md` + `wiki/backlog/research-gaps.md` + recent session logs.\n\n")
    out.append("---\n\n")

    odq = PROJECT_ROOT / "wiki" / "backlog" / "operator-decision-queue.md"
    if odq.exists():
        out.append("## From `wiki/backlog/operator-decision-queue.md`\n\n")
        out.append("Operator-decision-queue tracks decisions both ANSWERED (with rationale + when) and OPEN (with options + recommendations).\n")
        out.append("Live source: [`wiki/backlog/operator-decision-queue.md`](wiki/backlog/operator-decision-queue.md)\n\n")
        # Count
        text = odq.read_text()
        resolved_count = text.count("RESOLVED")
        out.append(f"- Resolved decisions detected (rough count): {resolved_count}\n\n")

    gaps = PROJECT_ROOT / "wiki" / "backlog" / "research-gaps.md"
    if gaps.exists():
        out.append("## From `wiki/backlog/research-gaps.md`\n\n")
        out.append("Empirical questions requiring research/data.\n")
        out.append("Live source: [`wiki/backlog/research-gaps.md`](wiki/backlog/research-gaps.md)\n\n")

    # Cross-reference to most recent session log's open decisions
    log_dir = PROJECT_ROOT / "wiki" / "log"
    if log_dir.exists():
        recent_logs = sorted(log_dir.glob("2026-*.md"), reverse=True)[:3]
        if recent_logs:
            out.append("## Recently surfaced (from latest 3 session logs)\n\n")
            for p in recent_logs:
                out.append(f"- [`{p.name}`](wiki/log/{p.name})\n")
            out.append("\n")

    out.append("---\n\n")
    out.append("## How /questions consumes this\n\n")
    out.append("Operator's `/questions` slash command (root-propagated) reads this snapshot ")
    out.append("PLUS the live sources to render the interactive question-resolution mode. ")
    out.append("Per the `/view` mini-RFC convention, each unanswered question should surface with:\n\n")
    out.append("- The question stated\n")
    out.append("- Why it's open\n")
    out.append("- What it gates\n")
    out.append("- Options (2-4) with pros/cons/effort/risk\n")
    out.append("- Recommendation + reasoning\n")
    out.append("- What unblocks the decision\n\n")
    return "".join(out)


# ─────────── regen: vision.md ────────────


def regen_vision() -> str:
    out = []
    out.append("# Vision — Long-term Mission + Strategic Direction\n\n")
    out.append(f"_Auto-regenerated by `tools.state regenerate` at {now_iso()}._\n\n")
    out.append("---\n\n")

    # Anti-vendor-lock-in mission lesson
    avl = PROJECT_ROOT / "wiki" / "lessons" / "02_synthesized" / "anti-vendor-lock-in-is-an-empirical-claim-when-every-stack-layer-has-paper-evidence.md"
    if avl.exists():
        out.append("## Mission claim: Anti-Vendor-Lock-In\n\n")
        out.append("Source: [`wiki/lessons/02_synthesized/anti-vendor-lock-in-is-an-empirical-claim-when-every-stack-layer-has-paper-evidence.md`](wiki/lessons/02_synthesized/anti-vendor-lock-in-is-an-empirical-claim-when-every-stack-layer-has-paper-evidence.md)\n\n")
        # Extract just the Summary section
        text = avl.read_text()
        summary_start = text.find("## Summary")
        if summary_start > 0:
            next_section = text.find("\n## ", summary_start + 1)
            if next_section > 0:
                out.append(text[summary_start:next_section].strip() + "\n\n")

    # Custom-tailored model group (the operator's stack vision)
    ctmg = PROJECT_ROOT / "wiki" / "domains" / "cross-domain" / "custom-tailored-senior-engineer-tier-model-group-with-recreated-intelligence-layer-research-synthesis.md"
    if ctmg.exists():
        out.append("## Stack vision: Custom-Tailored Senior-Engineer-Tier Model Group\n\n")
        out.append("Source: [`wiki/domains/cross-domain/custom-tailored-senior-engineer-tier-model-group-with-recreated-intelligence-layer-research-synthesis.md`](wiki/domains/cross-domain/custom-tailored-senior-engineer-tier-model-group-with-recreated-intelligence-layer-research-synthesis.md)\n\n")
        text = ctmg.read_text()
        summary_start = text.find("## Summary")
        if summary_start > 0:
            next_section = text.find("\n## ", summary_start + 1)
            if next_section > 0:
                out.append(text[summary_start:next_section].strip() + "\n\n")

    out.append("---\n\n")
    out.append("## Strategic anchors (always-current)\n\n")
    out.append("- **Behave FROM the project, not OVER it** (operator-doctrinal 2026-04-24)\n")
    out.append("- **The project IS intelligent; intelligence comes from USING the project** (2026-04-24)\n")
    out.append("- **Pull the level from the frontier and remain independent** (2026-05-09)\n")
    out.append("- **Spec-driven development + strong methodology + standards** (2026-05-05)\n")
    out.append("- **PROFILES plural per project; each is ONE focused assistant job** (2026-05-09 turn 6)\n")
    out.append("- **A Profile is way more than just setting for one tool** (2026-05-09 turn 4)\n")
    return "".join(out)


# ─────────── regen: focus.md ────────────


def regen_focus() -> str:
    out = []
    out.append("# Focus — Current session + active arc\n\n")
    out.append(f"_Auto-regenerated by `tools.state regenerate` at {now_iso()}._\n\n")
    out.append("---\n\n")

    # Most recent operator directive
    notes_dir = PROJECT_ROOT / "raw" / "notes"
    if notes_dir.exists():
        recent_notes = sorted(notes_dir.glob("2026-*.md"), reverse=True)[:5]
        if recent_notes:
            out.append("## Most recent operator directives (last 5)\n\n")
            for p in recent_notes:
                title = ""
                try:
                    with open(p) as f:
                        for line in f:
                            if line.startswith("title:"):
                                title = line[6:].strip().strip('"').strip("'")[:120]
                                break
                except Exception:
                    pass
                out.append(f"- `{p.name}`\n  {title}\n")
            out.append("\n")

    # Most recent session log
    log_dir = PROJECT_ROOT / "wiki" / "log"
    if log_dir.exists():
        recent_logs = sorted(log_dir.glob("2026-*.md"), reverse=True)[:1]
        if recent_logs:
            out.append("## Most recent session log\n\n")
            out.append(f"- [`{recent_logs[0].name}`](wiki/log/{recent_logs[0].name})\n\n")

    # Active /opt-meta-layer queue (the current arc)
    out.append("## Active arc (Per-Project Assistant Profile work, 2026-05-09)\n\n")
    out.append("| # | Artifact | Status |\n|---|---|---|\n")
    out.append("| T084 | Profile Standards | ✅ done |\n")
    out.append("| T085 | Profile Model (spine) | ✅ done |\n")
    out.append("| T086 | Profile-Knowledge Integration | ✅ done |\n")
    out.append("| T087 | Spine Super-Model update | operator-approval territory |\n")
    out.append("| — | /opt Continuous Research Profile (Profile YAML + OpenClaw vendor) | ✅ deployable files at `.assistant/` |\n")
    out.append("| — | `tools/assistant.py` lifecycle CLI | ✅ done |\n")
    out.append("| — | `.cursor/` state surface | ✅ done (this file) |\n")
    out.append("\n")
    return "".join(out)


# ─────────── regen: trace.md ────────────


def regen_trace() -> str:
    out = []
    out.append("# Trace — Recent operator-AI interaction summary\n\n")
    out.append(f"_Auto-regenerated by `tools.state regenerate` at {now_iso()}._\n\n")
    out.append("---\n\n")

    # Recent raw/notes (verbatim directives)
    notes_dir = PROJECT_ROOT / "raw" / "notes"
    if notes_dir.exists():
        recent = sorted(notes_dir.glob("2026-*.md"), reverse=True)[:10]
        out.append(f"## Recent operator directives (last {len(recent)} verbatim logs)\n\n")
        for p in recent:
            out.append(f"- `{p.name}`\n")
        out.append("\n")

    # Recent commits
    out.append("## Recent commits (last 15)\n\n```\n")
    out.append(git("log", "--oneline", "-15") + "\n")
    out.append("```\n\n")

    return "".join(out)


# ─────────── regen entrypoint ────────────

REGENERATORS = {
    "view": ("view-snapshot.md", regen_view),
    "questions": ("questions-snapshot.md", regen_questions),
    "vision": ("vision.md", regen_vision),
    "focus": ("focus.md", regen_focus),
    "trace": ("trace.md", regen_trace),
}


def cmd_regenerate(args: argparse.Namespace) -> int:
    CURSOR_DIR.mkdir(parents=True, exist_ok=True)
    targets = list(REGENERATORS.keys()) if args.target == "all" else [args.target]
    meta = load_meta()
    meta.setdefault("files", {})
    for tgt in targets:
        if tgt not in REGENERATORS:
            print(f"Unknown target: {tgt} (known: {list(REGENERATORS.keys()) + ['all']})", file=sys.stderr)
            return 1
        filename, fn = REGENERATORS[tgt]
        print(f"  regenerating .cursor/{filename}...")
        content = fn()
        (CURSOR_DIR / filename).write_text(content)
        meta["files"][filename] = {
            "last_regenerated": now_iso(),
            "regenerated_by": regenerator(),
            "size_bytes": len(content.encode()),
        }
    meta["last_regenerated"] = now_iso()
    meta["regenerated_by"] = regenerator()
    meta["regeneration_count"] = meta.get("regeneration_count", 0) + 1
    save_meta(meta)
    print(f"  ✓ Done. Meta: {META_PATH}")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    meta = load_meta()
    print(f"Cursor state at {CURSOR_DIR}")
    print(f"Last regenerated: {meta.get('last_regenerated', '(never)')}")
    print(f"Regenerated by:   {meta.get('regenerated_by', '(n/a)')}")
    print(f"Total regens:     {meta.get('regeneration_count', 0)}")
    print()
    print(f"{'File':<30} {'Last regenerated':<22} {'Size'}")
    print(f"{'-' * 30} {'-' * 22} {'-' * 8}")
    for fname, info in meta.get("files", {}).items():
        print(f"{fname:<30} {info.get('last_regenerated') or '(never)':<22} {info.get('size_bytes', 0)} bytes")
    return 0


def cmd_show(args: argparse.Namespace) -> int:
    p = CURSOR_DIR / args.file
    if not p.exists():
        print(f"Not found: {p}", file=sys.stderr)
        return 1
    print(p.read_text())
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(prog="state", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    sp = sub.add_parser("regenerate", help="Regenerate .cursor/ files")
    sp.add_argument("target", nargs="?", default="all", help="all | view | questions | vision | focus | trace")
    sp.set_defaults(func=cmd_regenerate)
    sp = sub.add_parser("status", help="What's stale in .cursor/")
    sp.set_defaults(func=cmd_status)
    sp = sub.add_parser("show", help="Print a .cursor/ file")
    sp.add_argument("file")
    sp.set_defaults(func=cmd_show)
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
